schema:
  variables:
    DATABASE_URL:
      required: true
      type: string
      default: ""
      description: "Database URL"
    API_KEY:
      required: true
      type: string
      default: ""
      description: "API key"

rules:
  require_all: true
  allow_extra: false

adapters:
  - name: "aws"
    config:
      region: "us-west-2"
      parameter_store_prefix: "/envsync/test/"
